spring:
  profiles:
    active: @profileActive@

mybatis:
  mapper-locations:  classpath:mapper/*.xml,classpath:mapper/**/*.xml

logging:
  file:
    name: /data/app/logs/${artifactId}/${artifactId}.log
    max-size: 10MB